# Generated by Django 4.2.27 on 2026-01-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_core_app', '0003_remove_document_name_remove_document_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
